include ../.applTop
include $(APPLIC_TOP)/config/CONFIG

# Create an alarm file for TOP (i.e. if top = tcs:, then TOP = tcs)

TOP = ecs

# Alarm handler files to put into the DATA directory

DATA = $(TOP).config

include $(APPLIC_TOP)/config/RULES.Build


$(TOP).config: ../$(TOP).alh
	sed -e 's/$$(top)/$(TOP):/' $^ > $@
